#!/bin/bash

# Get all MX hosts for the domain
dig $1 MX +short | while read line; do
    # Remove the priority number for each MX host
    mxhost=$(echo $line | cut -d" " -f2)

    echo "MX-host: $mxhost"
    
    # Find the IP for each MX host
    for ip in $(dig $mxhost +short); do
        echo "    IP: $ip"
        
        # Do a reverse lookup of the MX host's IP
        for revhost in $(dig -x $ip +short); do
            echo "        reverse lookup: $revhost"
        done
    done
done

echo

dig $1 TXT +short | while read line; do
    for spfhost in $(echo $line | grep -Eoi "(include|ip[46]):\S+" | cut -d":" -f2- | cut -d"/" -f1); do
        echo "SPF host: $spfhost"
        echo $spfhost | grep -Eq "\S+\.[a-z]+"
        if [ $? -eq 0 ]; then
            # Is hostname
            for ip in $(dig $spfhost +short); do
                echo "    IP: $ip"
                
                # Do a reverse lookup of the MX host's IP
                for revhost in $(dig -x $ip +short); do
                    echo "        reverse lookup: $revhost"
                done
            done
        else
            # Is IP
            for revhost in  $(dig -x $spfhost +short | tr '\n' ' '); do
                echo "    reverse lookup: $revhost"
            done
        fi
    done
done
